### ISSUE TITLE
Script Error for Joomla 3.5x

### ISSUE THREAD

**Issue by kirancheema** [elinw/AssetDiagnosis#1]
Hi Thanks for creating and sharing this script.

I have found that the error below is appearing of you try and use the script with Joomla 3.x

Fatal error: Class 'Joomla\Application\AbstractApplication' not found in XXX_\libraries\joomla\application\base.php on line 23

**Comment by PierreCorell** [comment]
Hello.
thanks for your comment,

At the moment the script is not Joomla 3.5 ready.

**Comment by kirancheema** [comment]
no worries, just thought I would report the error.
